@startuml
hide empty members

!$branch="fix-input_of_instructional_records" 
!procedure $include($source)
  !include https://github.com/popoposorara/ERP_ER/blob/$branch/Entity/$source?raw=true
!endprocedure

namespace "指導要録入力" as input_of_instructional_records {

$include("ER_Customer.pu")

$include("ER_StudentRecord.pu")
$include("ER_StudentRecordComment.pu")
$include("ER_StudentRecordCommentAttendance.pu")
$include("ER_StudentRecordCommentIntegratedLearningTimeActivity.pu")
$include("ER_StudentRecordCommentSpecialActivities.pu")
$include("ER_StudentRecordCommentSpecialActivitiesContent.pu")
$include("ER_StudentRecordCommentVariousMatters.pu")
$include("ER_StudentRecordCommentRecordOfAction.pu")
$include("ER_StudentRecordCommentRecordOfActionContent.pu")
$include("ER_StudentRecordCommentRecordOfActionForIntellectualDisabilities.pu")
$include("ER_StudentRecordCommentRecordOfIndependenceActivity.pu")
$include("ER_StudentRecordCommentDisabilityStatus.pu")

$include("ER_Staff.pu")
$include("ER_Student.pu")

}

!include https://github.com/popoposorara/ERP_ER/blob/mana-input_of_instructional_records/Mana/UserManagement_package.pu_generated?raw=true
!include https://github.com/popoposorara/ERP_ER/blob/mana-input_of_instructional_records/Mana/UserManagement_relation.pu?raw=true


ER_StudentRecord ||--|| ER_Student
ER_StudentRecord ||--|| ER_StudentRecordComment
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentAttendance
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentIntegratedLearningTimeActivity
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentSpecialActivities
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentVariousMatters
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentRecordOfAction
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentRecordOfActionForIntellectualDisabilities
ER_StudentRecordComment ||--o{ ER_StudentRecordCommentRecordOfIndependenceActivity
ER_StudentRecordComment ||--|| ER_StudentRecordCommentDisabilityStatus
ER_StudentRecordCommentSpecialActivities ||--|| ER_StudentRecordCommentSpecialActivitiesContent
ER_StudentRecordCommentRecordOfAction ||--|| ER_StudentRecordCommentRecordOfActionContent
ER_StudentRecord ||--|{ ER_Staff

ER_Student ||--|| ER_Customer
ER_Customer ||--|| Mana_User
ER_Student ||--|| Mana_Student
ER_Staff ||--|| Mana_Teacher

@enduml