@startuml

entity "ER_StudentRecordCommentDisabilityStatus"{
    + student_record_comment_disability_status_id:入学時の障害の状態ID
    + :内容
}
note bottom
指導要録（参考様式）における下記の項目で利用
  - 入学時の障害の状態
end note

note bottom
指導要録（参考様式）における下記で利用
- ［知的障害者以外の特別支援学校］小学部児童指導要録
- ［知的障害者以外の特別支援学校］中学部生徒指導要録
- ［知的障害者以外の特別支援学校］高等部生徒指導要録
- ［知的障害者］小学部児童指導要録
- ［知的障害者］中学部生徒指導要録
- ［知的障害者］高等部生徒指導要録
end note

@enduml