@startuml

entity "ER_StudentRecordCommentRecordOfIndependenceActivity"{
    + student_record_comment_recode_of_independence_activity_id:自立活動の記録ID
    + grade:学年<optinal>
    + year:年度<optinal>
    + content:内容
}

note bottom
指導要録（参考様式）における下記の項目で利用
  - 自立活動の記録
end note

note bottom
指導要録（参考様式）における下記で利用
- ［知的障害者以外の特別支援学校］小学部児童指導要録
- ［知的障害者以外の特別支援学校］中学部生徒指導要録
- ［知的障害者以外の特別支援学校］高等部生徒指導要録
end note

@enduml