@startuml

entity "ER_Staff"{
    + staff_id:社員ID
    + mana_teacher_id:保護者ID -> mana_teacher_id
    + user_id:ユーザID -> user_id
    + code:社員番号
    + branch_id:所属校舎ID -> branch_id
    - kname1:氏名<姓> → (delete)@mana_user_id
    - kname2:氏名<名> → (delete)@mana_user_id
    - fname1:フリガナ<姓> → (delete)@mana_user_id
    - fname2:フリガナ<名> → (delete)@mana_user_id
    + staff_type:役割 → 10:社員 20:講師 30:スクールスタッフ
    + pre_staff_type:応募区分
    * teachable:授業可能フラグ
    - tel:電話番号 → (delete)@mana_user_id
    - portable_tel:携帯番号 → (delete)@mana_user_id
    - sex:性別 → (delete)@mana_user_id
    - birthday:生年月日 → (delete)@mana_user_id
    - zip_cd:郵便番号 → (delete)@mana_user_id
    - pref_id:都道府県ID -> prefecture_id → (delete)@mana_user_id
    - address1:住所1 → (delete)@mana_user_id
    - address2:住所2 → (delete)@mana_user_id
    - address3:住所3 → (delete)@mana_user_id
    - email:メールアドレス → (delete)@mana_user_id
    - portable_email:携帯メールアドレス → (delete)@mana_user_id
    + comment:備考
    + junior_high_school_id:中学校 -> school_id
    + high_school_id:高校 -> school_id
    + university_id:大学 -> school_id
    + grad_school_id:大学院 -> school_id
    + apply_grade:応募学年
    + recruit_reporting_method:連絡手法
    * station_name:最寄駅
    * railway_id:鉄道ID -> railway_id
    * route_id:路線ID -> route_id
    + careers_date:採用日付
    + correct_teacher_no:添削講師番号
    + resume_no:履歴書管理番号
    * health_check_receipt:健康診断受取有無
    + paper_pass:書類合格有無
    + mvcl_status:適性検査<MVCL>実施状況
    + leaved:退職
    + leave_date:退職日
    + interview_rating:面接評価
    + company_output:COMPANY連携出力
    + regist_changed_at:登録票更新日
    + main_subject_code:メイン科目コード
    + deleted:削除フラグ
    + stamp_id:印影ID -> stamp_id
    + simple_stamp_id:認印ID -> stamp_id
    + use_adjust_date:利用調整日
    + created_at:登録日時 → current_timestamp
    + created_by:登録者
    + updated_at:更新日時
    + updated_by:更新者
}

@enduml