@startuml

entity "ER_StudentRecordCommentAttendance"{
    + student_record_comment_attendance_id:出席ID
    + student_id : 生徒ID
    + year:年度
    + school_type:学校区分
    + lesson_num:授業日数
    + rest_num:休学日数
    + suspend_num:出席停止日数
    + mourning_num:忌引き日数
    + abroad_num:留学授業日数
    + abs_illness_num:病欠日数
    + abs_accident_num1:事故欠<届>
    + abs_accident_num2:事故欠<無>
    + remarks:備考
    + created_at:登録日時
    + created_by:登録者
    + updated_at:更新日時
    + updated_by:更新者
}

note bottom
指導要録（参考様式）における下記の項目で利用
  - 出欠の記録
end note

note bottom
指導要録（参考様式）における下記で利用
- 小学校指導要録
- 中学校指導要録
- 高等学校（全日制の課程・定時制の課程）指導要録
- 高等学校（通信制の課程）指導要録
- ［知的障害者以外の特別支援学校］小学部児童指導要録
- ［知的障害者以外の特別支援学校］中学部生徒指導要録
- ［知的障害者以外の特別支援学校］高等部生徒指導要録
- ［知的障害者］小学部児童指導要録
- ［知的障害者］中学部生徒指導要録
- ［知的障害者］高等部生徒指導要録
end note



@enduml
