@startuml

entity "Mana_SchoolInfo" {
    + mana_school_id -> mana_school_id
    + school_name
    + school_name_phonetic
    + mana_school_level_id -> mana_school_level_id
    + prefecture
    + city
    + is_archived:アーカイブ済みかどうか
    + resource_path:リソースパス
    # school_type:学校種別<国立/私立/公立>(add)
}

@enduml
