@startuml

entity "Mana_Student" {
    + mana_student_id:生徒ID
    + current_grade:現在の学年
    + student_enrollment_status: 在籍状況
    + mana_student_external_id : 生徒外部ID -> mana_student_id
    + student_note: 特記事項?
    + resource_path:
    + previous_grade:
}

@enduml
