@startuml

entity "branch" {
    + branch_id:校ID
    + company_type:本部区分 → _named_value【company_type】参照
    + code:コード
    + sort:並び順
    + name:校舎名
    + short_name:校舎名略称
    + fname:校舎名カナ → 講師管理系処理の検索で使用
    + tel:電話番号
    + fax:FAX番号
    + zip_cd:郵便番号
    + pref_id:都道府県ID → _named_value【prefecture】参照
    + address1:住所1
    + address2:住所2
    + address3:住所3
    + tel2:電話番号<キャリア>
    + fax2:FAX番号<キャリア>
    + zip_cd2:郵便番号<キャリア>
    + pref_id2:都道府県ID<キャリア>
    + address1_2:住所1<キャリア>
    + address2_2:住所2<キャリア>
    + address3_2:住所3<キャリア>
    + bill_lock:請求ロック → true:校の収納処理を止める
    + head_staff_id:責任者ID
    + branch_type:校区分 → 1:校 2:本部 3:倉庫
    + management_type:管理区分 → 1:直営 2:法人
    + open_date:開校日
    + close_date:閉校日
    + email:メールアドレス
    + short_tel:短縮番号
    + capacity:スクーリング最大人数 → スクーリングの上限に利用
    + school_flg:高校フラグ → true:高校
    + school_branch_id:高校ID
    + interview_count:面談件数
    + stamp_id:印影ID → 高校のみ
    + select_school_flg:高校選択可能フラグ
    + t_branch_code:高萩校コード → レポート連携用
    + y_branch_code:養父校コード → レポート連携用
    + s_branch_code: 専科校コード → レポート連携用
    + d_branch_code:DWO2校コード → HP連携用
    + c_branch_code: 専カレ校コード → 専カレ用
    + corporate_college_flg:法人校専カレフラグ
    + school_code:高校コード → 高校<高萩、養父>のみ登録される。※証明 書用
    + deleted:削除フラグ
    + certificate_lock:証明書承認ロック → true:証明書承認を止める
    + created_at:登録日時
    + created_by:登録者
    + updated_at:更新日時
    + updated_by:更新者
}

@enduml