@startuml
hide empty members

!$branch="main" 
!procedure $include($source)
  !include https://github.com/popoposorara/ERP_ER/blob/$branch/Entity/$source?raw=true
!endprocedure

namespace "調査書入力（進学用）" as research_form_entry_for_further_education {

$include("branch.pu")
$include("customer.pu")
$include("student_record.pu")
$include("student_record_comment.pu")
$include("staff.pu")
$include("student.pu")

$include("student_record_comment_attendance.pu")
$include("student_record_comment_special_activities.pu")
$include("student_record_comment_various_matters.pu")
$include("student_record_comment_integrated_learning_time_content.pu")

}

student_record ||--|| student
student_record ||--|| student_record_comment
student_record_comment ||--o{ student_record_comment_attendance
student_record_comment ||--o{ student_record_comment_special_activities
student_record_comment ||--o{ student_record_comment_various_matters
student_record_comment ||--o| student_record_comment_integrated_learning_time_content
student_record ||--|{ staff

@enduml