@startuml
hide empty members

!$branch="research_form_entry2" 
!procedure $include($source)
  !include https://github.com/popoposorara/ERP_ER/blob/$branch/Entity/$source?raw=true
!endprocedure

package "調査書入力（就職用）" as research_form_entry_for_employment {

$include("branch.pu")
$include("customer.pu")
$include("student_record.pu")
$include("student_record_comment.pu")
$include("staff.pu")
$include("student.pu")

$include("student_record_comment_special_activities.pu")
$include("student_record_comment_attendance.pu")
$include("student_medical_checkup.pu")
$include("student_strengths.pu")

}

student_record ||--|| student
student_record ||--|| student_record_comment
student_record_comment ||--|{ student_record_comment_special_activities
student_record_comment ||--|{ student_record_comment_attendance
student_record_comment ||--o| student_medical_checkup
student_record_comment ||--o| student_strengths
student_record ||--|{ staff

@enduml