@startuml
hide empty members

!include https://github.com/popoposorara/ERP_ER/blob/main/Mana/UserManagement_package.pu_generated?raw=true
!include https://github.com/popoposorara/ERP_ER/blob/main/Mana/UserManagement_relation.pu?raw=true

@enduml