name: Auto Generate
on:
  push:
    branches: [ main ]
  status: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Run Script
      env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
      run: |
        kotlinc -script ./.github/workflows/AutoGenerate.kts  -- -b $BRANCH_NAME
    - name: commit & push
      run: |
        git add -N . # 新規ファイルを含める
        if ! git diff --exit-code --quiet
        then
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "generate file"
          git push
        fi
           